#!/usr/bin/env python2

import sys, hashlib
torrent = open( sys.argv[1] )
try:
    content = torrent.read()
    position = content.find('4:info')
    content = content[ position + 6 : -1 ]
    magnet = "magnet:?xt=urn:btih:" + hashlib.sha1(content).hexdigest().upper()
    print magnet
finally:
    torrent.close()
