#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import pygtk
pygtk.require('2.0')
import gtk
import os
import urllib
import chardet

def alert(msg):
    dialog = gtk.MessageDialog()
    dialog.set_markup(msg)
    dialog.run()

def main():
    selected = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS')
    files = selected.splitlines()
    for file in files:
        curitem = file.split('/')[-1]
        curpath = file[:-len(curitem)]
        encoding = chardet.detect(urllib.unquote(curitem))['encoding']
        newitem = urllib.unquote( curitem ).decode(encoding)
        os.rename(file, curpath+newitem)

if __name__ == "__main__":
    main()
