#!/usr/bin/env python2
# -*- coding: utf-8 -*-

__author__ = 'onisuly'

import os

selected = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS')
files = selected.splitlines()
for file in files:
    os.system('ln -s %s ~/Desktop' % file)
